import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import Header from "../../components/Header"
import NewHeader from "../../components/NewHeader"
import LotteryEntrance from "../../components/LotteryEntrance"

export default function Home() {
    return (
        <>
            <Head>
                <title>Decentralized Lottery</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NewHeader />
            <LotteryEntrance/>
            Hello!
        </>
    )
}
